# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
# 其他数据库连接配置
spring:
  datasource:
    ...
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5

spring:
  jpa:
    hibernate:
      ddl-auto: update

# 其他应用配置
spring:
  application:
    name: my-application
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  logging:
    level:
      root: INFO
      org.springframework: INFO
      com.example: DEBUG
